version: '3.8'

services:

  bv.server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - bv.mysql
    container_name: bv.server
    environment:
      - FLASK_ENV=development
    command: flask run -h 0.0.0.0 --debug
    stdin_open: true
    ports:
      - '5001:5000'
    volumes:
      - ./server:/app
    networks:
      - bv.network

  client:
    build:
      context: ./client
      target: 'develop-stage'
      dockerfile: Dockerfile
    container_name: bv.client
    ports:
      - 8000:5173
    restart: unless-stopped
    volumes:
      - './client:/app'
      - /app/node_modules
    tty: true
    networks:
      - bv.network

  bv.mysql:
    image: mysql:8.0
    container_name: bv.mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/data/db:/var/lib/mysql
    restart: always
    networks:
      - bv.network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3311:3306"

volumes:
  bv.mysql:

networks:
  bv.network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.5.0/25
